name: core
description: A new Flutter package project.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  restaurant:
    path: ../restaurant

  asn1lib: ^1.5.0

  # https://pub.dev/packages/firebase_analytics
  firebase_analytics: ^10.7.2
  # https://pub.dev/packages/firebase_core
  firebase_core: ^2.24.0
  # https://pub.dev/packages/firebase_crashlytics
  firebase_crashlytics: ^3.4.6
  # https://pub.dev/packages/firebase_messaging
  firebase_messaging: ^14.7.6
  # https://pub.dev/packages/firebase_remote_config
  firebase_remote_config: ^4.3.6

  flutter_cache_manager: ^3.3.1
  #https://pub.dev/packages/flutter_secure_storage
  flutter_secure_storage: ^9.0.0

  get_it: ^7.6.4


  #https://pub.dev/packages/dio
  dio: ^5.3.3
  #https://pub.dev/packages/flutter_local_notifications/
  flutter_local_notifications: ^16.1.0
  pretty_dio_logger: ^1.3.1
  sqflite: ^2.3.0
  #https://pub.dev/packages/permission_handler
  permission_handler: ^11.0.0
  # https://pub.dev/packages/flutter_sizer
  flutter_sizer: ^1.0.5
  #https://pub.dev/packages/go_router
  go_router: ^12.1.3
  # https://pub.dev/packages/shimmer
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:


