// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYGiwmTuFMZ8Ju6Hv1LC8VUcEx1pPY-iU',
    appId: '1:324918319550:web:1d7cb72b3d96a5f38501ef',
    messagingSenderId: '324918319550',
    projectId: 'myfirebase-ab761',
    authDomain: 'myfirebase-ab761.firebaseapp.com',
    databaseURL: 'https://myfirebase-ab761.firebaseio.com',
    storageBucket: 'myfirebase-ab761.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJLmHH4Hg02Gb6wniAscPoENtjRVaWtc0',
    appId: '1:324918319550:android:2c2f661e2c9c49a48501ef',
    messagingSenderId: '324918319550',
    projectId: 'myfirebase-ab761',
    databaseURL: 'https://myfirebase-ab761.firebaseio.com',
    storageBucket: 'myfirebase-ab761.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmDZSF9E_9smlrLL_lySrP76KjmEof9L4',
    appId: '1:324918319550:ios:7f89e98c121b26cd8501ef',
    messagingSenderId: '324918319550',
    projectId: 'myfirebase-ab761',
    databaseURL: 'https://myfirebase-ab761.firebaseio.com',
    storageBucket: 'myfirebase-ab761.appspot.com',
    androidClientId: '324918319550-3slkbgqbcdbtpvbgqmjou4uusrpf8mj3.apps.googleusercontent.com',
    iosClientId: '324918319550-522c6u2imbuv1mr1m01mmp6gk47sncka.apps.googleusercontent.com',
    iosBundleId: 'id.flutter.fundamental',
  );
}
